grafana:
  enabled: true
  
  persistence:
    enabled: true
    type: pvc
    accessModes:
    - ReadWriteOnce
    size: 4Gi
    finalizers:
    - kubernetes.io/pvc-protection

  ingress:
    enabled: true
    ingressClassName: nginx
    path: /grafana
  
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"

    datasources:
      enabled: true
      defaultDatasourceEnabled: true




additionalPrometheusRulesMap: 
  rule-name: 
    groups:
      - name: AllInstances
        rules: 
        - alert: InstanceDown
          expr: up == 0
          for: 1m
          annotations:
            title: 'Instance {{ $labels.instance }} down'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
          labels:
            application: 'bozobooks'
            source: 'prometheus'

        - alert: InstanceDown
          expr: up == 0
          for: 1m
          annotations:
            title: 'Instance {{ $labels.instance }} down'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
          labels:
            application: 'bozobooks'
            source: 'prometheus'


alertmanager:
  enabled: true
  ## Alertmanager configuration directives
  ## ref: https://prometheus.io/docs/alerting/configuration/#configuration-file
  ##      https://prometheus.io/webtools/alerting/routing-tree-editor/
  ##

  config:
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/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'
    route:
        receiver: 'slack-notifications'
        repeat_interval: 1s
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#monitoring'
        send_resolved: true
        title: "Alert: {{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "Alert: {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"