apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: book-library-postgres-db-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: linode-block-storage-retain
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  local:
    path: "/Users/hossam/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: book-library-postgres-db-pv-claim
  namespace: bozo-book-library-dev
  labels:
    app: book-library-postgres-db
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
