
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: book-library-postgres-db-pv-claim
  namespace: bozo-book-library-dev
  labels:
    app: book-library-postgres-db
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
